---
title: "monthly-site-meeting"
author: "Alex Gaffney"
date: "2025-05-13"
output: html_document
---

```{r libraries, include=FALSE}
library(readxl)
library(data.table)
library(stringr)
library(dplyr)
library(plotly)
library(ggplot2)
```


# Read in data
```{r}
# "C:\Users\AGaffney\Documents\CPF excel\CPF Study Data 2023_copy_2025_May.xlsx"
cpf_data_2023_4 <- read_excel("/Users/AGaffney/Documents/CPF excel/CPF Study Data 2023_copy_2025_May.xlsx", sheet = "2023-24")
cpf_data_2025 <- read_excel("/Users/AGaffney/Documents/CPF excel/CPF Study Data 2023_copy_2025_May.xlsx", sheet = "2025")
cpf_data <- rbind(cpf_data_2023_4,cpf_data_2025)
cpf_data <- as.data.table(cpf_data)
str(cpf_data)
```


# Tidy data
```{r}
cpf_data <- cpf_data %>%
  mutate(
    Consent = as.factor(Consent),
    `Consent Month` = factor(`Consent Month`, levels = month.abb),
    ga_weeks = as.numeric(sub("\\+.*", "", `GA at birth`)),
    Weight = as.numeric(gsub("kg|g","",tolower(Weight))),
    `HRCP Diagnosis` = as.factor(`HRCP Diagnosis`),
    `HRCP Diagnosis Date` = as.Date(`HRCP Diagnosis Date`),
    `CP Diagnosis` = as.factor(`CP Diagnosis`),
    `CP Diagnosis Date` = as.Date(`CP Diagnosis Date`)
  )
```
# N Eligble children born in past month
```{r}
target_month <- 4
target_year <- 2025

eligble <- cpf_data[year(DOB) == target_year & month(DOB) == target_month]
nrow(eligble)

```
# Eligble consent breakdown
```{r}
table(eligble$Consent)
```

# Preterm (n) born in past month
```{r}
nrow(eligble[ga_weeks < 37])
```

# GM writhing age performed in month
```{r}
cpf_data$`GMA-Writhing age` = tolower(cpf_data$`GMA-Writhing age`)

cpf_data %>%
  filter(str_detect(`GMA-Writhing age`, "april") & year(DOB) == target_year) 

# Missed?
```
# Visits at 3-4 months (n) in past month
```{r}
eligble$`Physio 3/12 date`
```
# GM fidgety age performed in month
```{r}
cpf_data$`GMA-Fidgety age` = tolower(cpf_data$`GMA-Fidgety age`)

cpf_data %>%
  filter(str_detect(`GMA-Fidgety age`, "april") & year(DOB) == target_year) 

```
# Diagnosis of CP in month
```{r}
cpf_data[year(`HRCP Diagnosis Date`) == target_year &
           month(`HRCP Diagnosis Date`) == target_month |
           year(`CP Diagnosis Date`) == target_year &
           month(`CP Diagnosis Date`) == target_month]
```


```{r}

```


```{r}

```


```{r}

```
